In [1]:
import numpy as np
from autograd import jacobian

In [2]:
func1 = lambda x: x[0] - 2*x[1] + 3*x[2] - 7
func2 = lambda x: 2*x[0] - x[1] + x[2] - 4
func3 = lambda x: -3*x[0] - 2*x[1] + 2*x[2] + 10

jac_func1 = jacobian(func1)
jac_func2 = jacobian(func2)
jac_func3 = jacobian(func3)

In [6]:
i = 0
error = 100
tol = 1e-12
maxiter = 1000
M = 3
N = 3

x_0 = np.array([1,1,1], dtype=float).reshape(N,1)
print(x_0)
fun_evaluate = np.array([func1(x_0),func2(x_0),func3(x_0)]).reshape(M,1)
print(fun_evaluate)

[[1.]
 [1.]
 [1.]]
[[-5.]
 [-2.]
 [ 7.]]


In [7]:
er = []
iter = []
while np.any(error > tol) and i < maxiter:
    func_evaluate = np.array([func1(x_0),func2(x_0),func3(x_0)]).reshape(M,1)
    flat_x_0 = x_0.flatten()
    jac = np.array([jac_func1(flat_x_0),jac_func2(flat_x_0),jac_func3(flat_x_0)])
    jac.reshape(M,N)

    x_new = x_0 - np.linalg.inv(jac)@func_evaluate
    error = (abs(x_new - x_0)/x_0)
    
    x_0 = x_new

    print(i)
    print(error)
    print('-'*10)

    er.append(error)
    iter.append(i)
    
    i += 1
    
print('The Solution is: {}'.format(x_new))
print("LHS of function 1: {}".format(np.around(func1(x_new),12)))
print("LHS of function 2: {}".format(np.around(func2(x_new),12)))
print("LHS of function 3: {}".format(np.around(func3(x_new),12)))

0
[[1.57142857]
 [6.85714286]
 [5.71428571]]
----------
1
[[5.18104078e-16]
 [5.65204449e-16]
 [5.29127569e-16]]
----------
The Solution is: [[2.57142857]
 [7.85714286]
 [6.71428571]]
LHS of function 1: [-0.]
LHS of function 2: [0.]
LHS of function 3: [-0.]
