In [2]:
x = lambda a : a + 10
print(x(5))

15


In [3]:
import numpy as np
import matplotlib.pyplot as plt
from autograd import grad, jacobian

In [4]:
func1 = lambda x: x[0] - 2*x[1] + 3*x[2] - 7
func2 = lambda x: 2*x[0] - x[1] + x[2] - 4
func3 = lambda x: -3*x[0] - 2*x[1] + 2*x[2] + 10

jac_func1 = jacobian(func1)
jac_func2 = jacobian(func2)
jac_func3 = jacobian(func3)

In [13]:
i = 0
error = 100
tol = 1e-12
maxiter = 1000
M = 3
N = 3

x_0 = np.array([1,1,1], dtype=float).reshape(N,1)
fun_evaluate = np.array([func1(x_0),func2(x_0),func3(x_0)]).reshape(M,1)
print(fun_evaluate)
flat_x_0 = x_0.flatten()
jac = np.array([jac_func1(flat_x_0),jac_func2(flat_x_0),jac_func3(flat_x_0)])
print(jac)
jac.reshape(N,M)
print(jac)

x_new = x_0 - np.linalg.inv(jac)@fun_evaluate

# error = x_new - x_0

[[-5.]
 [-2.]
 [ 7.]]
[[ 1. -2.  3.]
 [ 2. -1.  1.]
 [-3. -2.  2.]]
[[ 1. -2.  3.]
 [ 2. -1.  1.]
 [-3. -2.  2.]]


In [15]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[9])

9
